---
collections:
# Manadatoriy for our oneview management!
- hpe.oneview
# Tue Nov  9 03:30:05 PST 2021 mschreie@redhat.com
# i commented this out. As i do not know what it is needed for...
# - community.general
# maybe needed for vmware playbooks
## -  ansible.posix

# # With the collection name, version, and source options
# - name: my_namespace.my_other_collection
#   version: 'version range identifiers (default: ``*``)'
#   source: 'The Galaxy URL to pull the collection from (default: ``--api-server`` from cmdline)'


