---
- hosts: target_hosts
  gather_facts: no

  tasks:
    - name: debug hostvars
      debug: 
        var: hostvars

    - name: Get a server profile template
      hpe.oneview.oneview_server_profile_template_facts:
        #### FIXME this only works with one oneview node
        hostname: "{{ hostvars[oneview_host]ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        name: "{{ server_profile_template_name }}"

    - name: Print out all facts about server profile template
      debug: 
        var: server_profile_templates


