---
- hosts: oneview_hosts
  gather_facts: false

  tasks:
    - name: Gather facts about all Enclosures
      hpe.oneview.oneview_enclosure_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost

    - debug: var=enclosures

