---
- hosts: target_hosts
  gather_facts: no
  
  vars_file:
    ## FIXME: you could add whichprofile var and source
    # - files/{{ whichprofile }}_template.yml
    # => still same profiles for all nodes
    # => allow for different data sets named e.g. like each host 
    #    within template file 
    #    and choose when using 
    - files/standard_template.yml

  tasks:
    - name: Create a server profile template
      hpe.oneview.oneview_server_profile_template:
        hostname: "{{ hostvars[oneview_host].ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        # auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"

        state: present
        data:
          "{{profile_data}}"
        params:
          force: true
      delegate_to: localhost
      register: result
      run_once: true

    - debug: msg= "{{ result.msg }}"

    - name: Gather facts about the Server Profile Template by name
      hpe.oneview.oneview_server_profile_template_facts:
        hostname: "{{ hostvars[oneview_host].ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        # auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"

        name: "{{ server_profile_template_name }}"
      delegate_to: localhost

    - debug: var=server_profile_templates


