---
- hosts: target_hosts
  gather_facts: no

  tasks:
    - name: Gather facts about all Scopes
      hpe.oneview.oneview_scope_facts:
        hostname: "{{ hostvars[oneview_host].ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
      delegate_to: localhost

    - name: Gather facts about all Server Profile Templates
      hpe.oneview.oneview_server_profile_template_facts:
        hostname: "{{ hostvars[oneview_host].ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        scope: hpe_redhat
      delegate_to: localhost

    - name: Print out all facts about all profile templates
      debug: 
        var: server_profile_templates

    - name: Server Profile Template name which we search
      debug: 
        var: server_profile_template_name



    - name: Get a server profile template for target serves
      hpe.oneview.oneview_server_profile_template_facts:
        hostname: "{{ hostvars[oneview_host].ansible_host }}"
        username: "{{ oneview_username }}"
        password: "{{ oneview_password }}"
        auth_login_domain: "{{ oneview_domain }}"
        api_version: "{{ oneview_apiversion }}"
        name: "{{ server_profile_template_name }}"
        scope: hpe_redhat
      delegate_to: localhost

    - name: Print out all facts about server profile template
      debug: 
        var: server_profile_templates


