---
- hosts: target_hosts
  gather_facts: false
  
  tasks:
    - name: read ov_hardware_names from file
      include_vars:
        file: "/tmp/oneview_deployment.state"
        name: ovhostnamelist
      delegate_to: bastion21  

    - name: see what we got
      debug:
        msg: "{{ ovhostnamelist }}"
      #delegate_to: bastion21  

    - name: see what we got
      debug:
        msg: "{{ ovhostnamelist.g1 }}"
      delegate_to: bastion21  
